{"name": "test_user_login_failure[firefox]", "status": "passed", "description": "\n    Test case to verify failed login using invalid credentials.\n    ", "parameters": [{"name": "browser_type", "value": "'firefox'"}], "start": 1727301951231, "stop": 1727301952870, "uuid": "725fd878-3043-4961-9577-5c366b45c1c7", "historyId": "135cf2ebc60c7daad5737dbd6e6f3cec", "testCaseId": "17d3089194985caa2bc4fdc96dc1b569", "fullName": "tests.test_user_auth#test_user_login_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "MarvelDeviser"}, {"name": "thread", "value": "14264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}]}