{"name": "test_user_login_failure[chromium]", "status": "passed", "description": "\n    Test case to verify failed login using invalid credentials.\n    ", "parameters": [{"name": "browser_type", "value": "'chromium'"}], "start": 1727295379470, "stop": 1727295380478, "uuid": "06020d75-77e2-4be2-870f-4fe0d774b337", "historyId": "df7edcb30dcc084392721104227917d7", "testCaseId": "17d3089194985caa2bc4fdc96dc1b569", "fullName": "tests.test_user_auth#test_user_login_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "MarvelDeviser"}, {"name": "thread", "value": "15452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}]}